import { CanvasElement } from '../store/useStore';

/**
 * Advanced Export Utility for Studio Website Builder
 * Generates a production-ready standalone HTML file with Tailwind CSS and modern styling.
 */
export const exportToHTML = (elements: CanvasElement[]) => {
  // Helper to convert React-style camelCase styles to CSS kebab-case
  const formatStyles = (style: Record<string, any>) => {
    return Object.entries(style)
      .map(([key, value]) => {
        const property = key.replace(/[A-Z]/g, m => "-" + m.toLowerCase());
        // Handle numeric values that need units (px by default)
        const formattedValue = typeof value === 'number' && !['opacity', 'zIndex', 'fontWeight'].includes(key) 
          ? `${value}px` 
          : value;
        return `${property}: ${formattedValue}`;
      })
      .join('; ');
  };

  const elementsHTML = elements.map(el => {
    const styleString = formatStyles(el.style || {});
    const classString = (el.classes || []).join(' ');
    const attributes = Object.entries(el.attributes || {})
      .map(([key, value]) => `${key}="${value}"`)
      .join(' ');
    
    // Support image tags separately
    if (el.tag === 'img') {
        const src = (el.attributes as any)?.src || 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=2000';
        return `<img id="${el.id}" class="${classString}" style="${styleString}" src="${src}" alt="Generated content" ${attributes} />`;
    }

    return `<${el.tag} id="${el.id}" class="${classString}" style="${styleString}" ${attributes}>${el.content || el.innerHTML || ''}</${el.tag}>`;
  }).join('\n        ');

  const fullHTML = `<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Website generated by Studio - Minimalistic website builder.">
    <title>Studio Builder | Built for Excellence</title>
    
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    
    <!-- Styling Infrastructure -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    fontFamily: {
                        sans: ['Plus Jakarta Sans', 'sans-serif'],
                        mono: ['JetBrains Mono', 'monospace'],
                    },
                    colors: {
                        brand: {
                            50: '#f5f7ff',
                            100: '#ebf0fe',
                            200: '#dee7fe',
                            300: '#c4d5fd',
                            400: '#a1bcfa',
                            500: '#7a9df6',
                            600: '#6381f1',
                            700: '#5067e1', // Primary Indigo
                            800: '#4655b4',
                            900: '#3d4a8e',
                            950: '#262d54',
                        }
                    },
                    animation: {
                        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                    }
                }
            }
        }
    </script>
    
    <style type="text/tailwindcss">
        @layer base {
            body { 
                @apply bg-[#020617] text-slate-100 antialiased selection:bg-brand-500/30 selection:text-brand-200;
                font-feature-settings: "ss01", "ss02", "cv01", "cv02";
            }
        }
        @layer components {
            .glass-effect {
                @apply backdrop-blur-xl bg-white/5 border border-white/10 shadow-[0_8px_32px_0_rgba(0,0,0,0.37)];
            }
        }
    </style>
</head>
<body class="min-h-screen">
    <div id="root" class="relative overflow-x-hidden">
        <!-- Site Container -->
        <main class="site-wrapper relative z-10 w-full">
            ${elementsHTML}
        </main>

        <!-- Ambient Background -->
        <div class="fixed inset-0 pointer-events-none -z-10 bg-[radial-gradient(circle_at_top_right,#1e1b4b,transparent_50%),radial-gradient(circle_at_bottom_left,#000000,transparent_50%)]"></div>
    </div>
</body>
</html>`;

  const blob = new Blob([fullHTML], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `web-builder-site-${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
